import {
  CheckCircleOutlined,
  DeleteOutlined,
  KeyOutlined,
  PlayCircleOutlined,
  UnlockOutlined,
} from "@ant-design/icons";
import type { CavadaLabsFieldConfig, CavadaLabsResourceConfig, CavadaLabsRuntimeContext } from "./types";
import { enumOptions, toOptions } from "./utils";

const status = {
  company: enumOptions(["active", "suspended", "archived"]),
  project: enumOptions(["dev", "production", "archived"]),
  chatbot: enumOptions(["draft", "published", "disabled"]),
  node: enumOptions(["pending", "online", "degraded", "offline", "draining", "disabled"]),
  gpu: enumOptions(["available", "allocated", "loading", "loaded", "unhealthy", "offline", "disabled"]),
  runtime: enumOptions(["queued", "locking", "loading", "loaded", "failed", "expired", "unloading", "released"]),
  lock: enumOptions(["active", "released", "expired"]),
  ragCollection: enumOptions(["draft", "active", "archived"]),
  ragDocument: enumOptions(["queued", "indexing", "indexed", "failed", "deleted"]),
  assignment: enumOptions(["active", "disabled"]),
  compliance: enumOptions(["draft", "active", "published", "archived"]),
  guardrail: enumOptions(["draft", "active", "disabled", "archived"]),
  dsr: enumOptions([
    "received",
    "identity_verification",
    "in_progress",
    "waiting_customer",
    "completed",
    "rejected",
    "cancelled",
  ]),
};

const frameworkOptions = enumOptions(["gdpr", "ai_act", "security", "internal"]);
const jsonFormats = enumOptions(["json", "csv", "xlsx", "pdf"]);
const scopeOptions = enumOptions(["company", "project", "chatbot"]);
const ragScopeOptions = enumOptions(["company", "project"]);
const reasoningOptions = enumOptions(["none", "minimal", "low", "medium", "high"]);

const jsonField = (
  name: string,
  label: string,
  defaultValue: Record<string, any> = {},
  fullWidth = true,
): CavadaLabsFieldConfig => ({
  name,
  label,
  type: "json",
  defaultValue,
  fullWidth,
  rows: 5,
});

const companyField = (companyOptions: ReturnType<typeof toOptions>): CavadaLabsFieldConfig => ({
  name: "company_id",
  label: "Company",
  type: "select",
  required: true,
  options: companyOptions,
});

const projectField = (projectOptions: ReturnType<typeof toOptions>, required = true): CavadaLabsFieldConfig => ({
  name: "project_id",
  label: "Project",
  type: "select",
  required,
  options: projectOptions,
});

const chatbotField = (chatbotOptions: ReturnType<typeof toOptions>, required = false): CavadaLabsFieldConfig => ({
  name: "chatbot_id",
  label: "Chatbot",
  type: "select",
  required,
  options: chatbotOptions,
});

const collectionField = (collectionOptions: ReturnType<typeof toOptions>, required = false): CavadaLabsFieldConfig => ({
  name: "collection_id",
  label: "RAG collection",
  type: "select",
  required,
  options: collectionOptions,
});

export const buildCavadaLabsResourceConfigs = (
  context: CavadaLabsRuntimeContext,
): Record<string, CavadaLabsResourceConfig> => {
  const companyOptions = toOptions(context.companies, "company_id", "legal_name");
  const projectOptions = toOptions(context.projects, "project_id", "name");
  const chatbotOptions = toOptions(context.chatbots, "chatbot_id", "name");
  const collectionOptions = toOptions(context.ragCollections, "collection_id", "name");
  const nodeOptions = toOptions(context.nodes, "node_id", "display_name");

  const companyFilter = {
    name: "company_id",
    label: "Company",
    type: "select" as const,
    options: companyOptions,
  };
  const projectFilter = {
    name: "project_id",
    label: "Project",
    type: "select" as const,
    options: projectOptions,
  };

  return {
    companies: {
      key: "companies",
      title: "Companies",
      listPath: "/cavadalabs/companies",
      responseKey: "companies",
      rowKey: "company_id",
      createPath: "/cavadalabs/companies",
      createLabel: "New company",
      updatePath: (row) => `/cavadalabs/companies/${row.company_id}`,
      updateLabel: "Edit company",
      filters: [{ name: "status", label: "Status", type: "select", options: status.company }],
      createFields: [
        { name: "legal_name", label: "Legal name", type: "text", required: true },
        { name: "billing_name", label: "Billing name", type: "text" },
        { name: "vat_tax_id", label: "VAT / Tax ID", type: "text" },
        { name: "plan", label: "Plan", type: "text" },
        { name: "status", label: "Status", type: "select", options: status.company, defaultValue: "active" },
        { name: "monthly_budget", label: "Monthly budget", type: "number", min: 0, step: 0.01 },
        { name: "admin_emails", label: "Admin emails", type: "tags", fullWidth: true },
        jsonField("billing_address", "Billing address"),
        jsonField("retention_policy", "Retention policy"),
        jsonField("default_billing_settings", "Default billing settings"),
        jsonField("metadata", "Metadata"),
      ],
      updateFields: [
        { name: "legal_name", label: "Legal name", type: "text", required: true },
        { name: "billing_name", label: "Billing name", type: "text", emptyValue: "null" },
        { name: "vat_tax_id", label: "VAT / Tax ID", type: "text", emptyValue: "null" },
        { name: "plan", label: "Plan", type: "text", emptyValue: "null" },
        { name: "status", label: "Status", type: "select", options: status.company },
        { name: "monthly_budget", label: "Monthly budget", type: "number", min: 0, step: 0.01, emptyValue: "null" },
        { name: "admin_emails", label: "Admin emails", type: "tags", fullWidth: true },
        jsonField("billing_address", "Billing address"),
        jsonField("retention_policy", "Retention policy"),
        jsonField("default_billing_settings", "Default billing settings"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "legal_name", title: "Legal name", type: "text", width: 220 },
        { key: "company_id", title: "Company ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "plan", title: "Plan", type: "text", width: 120 },
        { key: "monthly_budget", title: "Monthly budget", type: "currency", width: 150 },
        { key: "admin_emails", title: "Admins", type: "tags", width: 240 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "archive",
          label: "Archive",
          danger: true,
          icon: <DeleteOutlined />,
          confirmTitle: "Archive company?",
          confirmDescription:
            "The company will be marked archived. Existing linked audit and billing history is preserved.",
          request: (row) => ({ method: "DELETE", path: `/cavadalabs/companies/${row.company_id}` }),
        },
      ],
    },
    projects: {
      key: "projects",
      title: "Projects",
      listPath: "/cavadalabs/projects",
      responseKey: "projects",
      rowKey: "project_id",
      createPath: "/cavadalabs/projects",
      createLabel: "New project",
      updatePath: (row) => `/cavadalabs/projects/${row.project_id}`,
      updateLabel: "Edit project",
      filters: [companyFilter, { name: "status", label: "Status", type: "select", options: status.project }],
      createFields: [
        companyField(companyOptions),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "status", label: "Status", type: "select", options: status.project, defaultValue: "dev" },
        { name: "budget", label: "Budget", type: "number", min: 0, step: 0.01 },
        { name: "allowed_models", label: "Allowed models", type: "tags", fullWidth: true },
        {
          name: "allowed_rag_collections",
          label: "Allowed RAG collections",
          type: "multiSelect",
          options: collectionOptions,
          fullWidth: true,
        },
        { name: "default_guardrail_policy", label: "Default guardrail policy", type: "text" },
        jsonField("default_chatbot_settings", "Default chatbot settings"),
        jsonField("retention_policy_override", "Retention policy override"),
        jsonField("metadata", "Metadata"),
      ],
      updateFields: [
        { name: "name", label: "Name", type: "text", required: true },
        { name: "status", label: "Status", type: "select", options: status.project },
        { name: "budget", label: "Budget", type: "number", min: 0, step: 0.01, emptyValue: "null" },
        { name: "allowed_models", label: "Allowed models", type: "tags", fullWidth: true },
        {
          name: "allowed_rag_collections",
          label: "Allowed RAG collections",
          type: "multiSelect",
          options: collectionOptions,
          fullWidth: true,
        },
        { name: "default_guardrail_policy", label: "Default guardrail policy", type: "text", emptyValue: "null" },
        jsonField("default_chatbot_settings", "Default chatbot settings"),
        jsonField("retention_policy_override", "Retention policy override"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 220 },
        { key: "project_id", title: "Project ID", type: "id", width: 220 },
        { key: "company_id", title: "Company", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "allowed_models", title: "Models", type: "tags", width: 260 },
        { key: "budget", title: "Budget", type: "currency", width: 130 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "archive",
          label: "Archive",
          danger: true,
          icon: <DeleteOutlined />,
          confirmTitle: "Archive project?",
          confirmDescription:
            "The project will be marked archived. Existing runtime, billing, and compliance history is preserved.",
          request: (row) => ({ method: "DELETE", path: `/cavadalabs/projects/${row.project_id}` }),
        },
      ],
    },
    chatbots: {
      key: "chatbots",
      title: "Chatbots",
      listPath: "/cavadalabs/chatbots",
      responseKey: "chatbots",
      rowKey: "chatbot_id",
      createPath: "/cavadalabs/chatbots",
      createLabel: "New chatbot",
      filters: [
        companyFilter,
        projectFilter,
        { name: "status", label: "Status", type: "select", options: status.chatbot },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "status", label: "Status", type: "select", options: status.chatbot, defaultValue: "draft" },
        { name: "default_language", label: "Default language", type: "text", defaultValue: "it" },
        { name: "prompt_version", label: "Prompt version", type: "number", min: 1, defaultValue: 1 },
        { name: "model_policy_id", label: "Model policy ID", type: "text" },
        {
          name: "system_prompt",
          label: "System prompt",
          type: "textarea",
          rows: 6,
          fullWidth: true,
          emptyValue: "emptyString",
        },
        {
          name: "assigned_rag_collections",
          label: "Assigned RAG collections",
          type: "multiSelect",
          options: collectionOptions,
          fullWidth: true,
        },
        { name: "assigned_guardrail_policy", label: "Assigned guardrail policy", type: "text" },
        { name: "allowed_domains", label: "Allowed domains", type: "tags", fullWidth: true },
        { name: "fallback_message", label: "Fallback message", type: "textarea", rows: 3, fullWidth: true },
        jsonField("widget_theme_config", "Widget theme config"),
        jsonField("transcript_retention_policy", "Transcript retention policy"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 220 },
        { key: "chatbot_id", title: "Chatbot ID", type: "id", width: 220 },
        { key: "project_id", title: "Project", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "default_language", title: "Language", type: "text", width: 100 },
        { key: "model_policy_id", title: "Policy", type: "id", width: 200 },
        { key: "allowed_domains", title: "Domains", type: "tags", width: 240 },
      ],
    },
    webTokens: {
      key: "webTokens",
      title: "Web tokens",
      listPath: "/cavadalabs/web-tokens",
      responseKey: "web_tokens",
      rowKey: "web_token_id",
      createPath: "/cavadalabs/web-tokens",
      createLabel: "Issue token",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        { name: "status", label: "Status", type: "select", options: enumOptions(["active", "revoked", "expired"]) },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions),
        chatbotField(chatbotOptions, true),
        { name: "name", label: "Name", type: "text" },
        { name: "allowed_domains", label: "Allowed domains", type: "tags", fullWidth: true },
        { name: "allowed_origins", label: "Allowed origins", type: "tags", fullWidth: true },
        {
          name: "route_allowlist",
          label: "Route allowlist",
          type: "tags",
          defaultValue: ["/cavadalabs/chatbots/messages"],
          fullWidth: true,
        },
        { name: "ip_rpm_limit", label: "IP RPM limit", type: "number", min: 1 },
        { name: "session_rpm_limit", label: "Session RPM limit", type: "number", min: 1 },
        { name: "session_budget", label: "Session budget", type: "number", min: 0, step: 0.01 },
        {
          name: "expires_in_seconds",
          label: "Expires in seconds",
          type: "number",
          min: 60,
          max: 86400,
          defaultValue: 3600,
        },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 180 },
        { key: "web_token_id", title: "Token ID", type: "id", width: 220 },
        { key: "token_prefix", title: "Prefix", type: "text", width: 100 },
        { key: "chatbot_id", title: "Chatbot", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "allowed_domains", title: "Domains", type: "tags", width: 220 },
        { key: "expires_at", title: "Expires", type: "datetime", width: 170 },
        { key: "last_used_at", title: "Last used", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "revoke",
          label: "Revoke",
          danger: true,
          icon: <UnlockOutlined />,
          confirmTitle: "Revoke web token",
          request: (row) => ({ method: "POST", path: `/cavadalabs/web-tokens/${row.web_token_id}/revoke` }),
        },
      ],
    },
    modelPolicies: {
      key: "modelPolicies",
      title: "Model policies",
      listPath: "/cavadalabs/model-policies",
      responseKey: "model_policies",
      rowKey: "policy_id",
      createPath: "/cavadalabs/model-policies",
      createLabel: "New policy",
      filters: [projectFilter],
      requiredFilters: ["project_id"],
      getInitialFilters: (runtimeContext) => ({
        project_id: runtimeContext.projects[0]?.project_id,
      }),
      createFields: [
        projectField(projectOptions),
        {
          name: "model_alias",
          label: "Model alias",
          type: "text",
          required: true,
          defaultValue: "cavadalabs/qwen3-32b",
        },
        {
          name: "provider",
          label: "Provider",
          type: "select",
          required: true,
          options: enumOptions(["cavadalabs", "openai", "anthropic", "azure", "gemini", "mistral", "custom"]),
          defaultValue: "cavadalabs",
        },
        { name: "deployment_id", label: "Deployment ID", type: "text" },
        { name: "priority", label: "Priority", type: "number", min: 1, required: true, defaultValue: 100 },
        { name: "enabled", label: "Enabled", type: "switch", defaultValue: true },
        { name: "fallback_enabled", label: "Fallback enabled", type: "switch", defaultValue: true },
        { name: "prefer_loaded_model", label: "Prefer loaded model", type: "switch", defaultValue: true },
        { name: "require_json_output", label: "Require JSON output", type: "switch", defaultValue: false },
        { name: "force_json_output", label: "Force JSON output", type: "switch", defaultValue: false },
        { name: "strict_json", label: "Strict JSON", type: "switch", defaultValue: false },
        { name: "repair_invalid_json", label: "Repair invalid JSON", type: "switch", defaultValue: false },
        { name: "retry_on_invalid_json", label: "Retry invalid JSON", type: "switch", defaultValue: false },
        { name: "require_no_think", label: "Require no-think", type: "switch", defaultValue: false },
        { name: "no_think", label: "No-think", type: "switch", defaultValue: false },
        { name: "reasoning_mode", label: "Reasoning mode", type: "select", options: reasoningOptions },
        { name: "hide_reasoning", label: "Hide reasoning", type: "switch", defaultValue: false },
        { name: "strip_thinking_tags", label: "Strip thinking tags", type: "switch", defaultValue: false },
        { name: "max_cost_input", label: "Max input cost", type: "number", min: 0, step: 0.000001 },
        { name: "max_cost_output", label: "Max output cost", type: "number", min: 0, step: 0.000001 },
        { name: "required_capabilities", label: "Required capabilities", type: "tags", fullWidth: true },
        jsonField("json_schema", "JSON schema", {}, true),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "model_alias", title: "Model", type: "text", width: 220 },
        { key: "policy_id", title: "Policy ID", type: "id", width: 220 },
        { key: "provider", title: "Provider", type: "status", width: 120 },
        { key: "priority", title: "Priority", type: "number", width: 90 },
        { key: "enabled", title: "Enabled", type: "boolean", width: 100 },
        { key: "fallback_enabled", title: "Fallback", type: "boolean", width: 100 },
        { key: "force_json_output", title: "JSON", type: "boolean", width: 90 },
        { key: "no_think", title: "No-think", type: "boolean", width: 100 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    nodes: {
      key: "nodes",
      title: "Nodes",
      listPath: "/cavadalabs/nodes",
      responseKey: "nodes",
      rowKey: "node_id",
      createPath: "/cavadalabs/nodes",
      createLabel: "New node",
      filters: [{ name: "status", label: "Status", type: "select", options: status.node }],
      createFields: [
        { name: "display_name", label: "Display name", type: "text", required: true },
        { name: "hostname", label: "Hostname", type: "text" },
        { name: "location", label: "Location", type: "text" },
        { name: "status", label: "Status", type: "select", options: status.node, defaultValue: "pending" },
        { name: "agent_version", label: "Agent version", type: "text" },
        {
          name: "allowed_project_ids",
          label: "Allowed projects",
          type: "multiSelect",
          options: projectOptions,
          fullWidth: true,
        },
        { name: "pools", label: "Pools", type: "tags", fullWidth: true },
        {
          name: "default_electricity_cost_per_kwh",
          label: "Electricity cost / kWh",
          type: "number",
          min: 0,
          step: 0.0001,
        },
        { name: "fixed_hourly_cost", label: "Fixed hourly cost", type: "number", min: 0, step: 0.0001 },
        {
          name: "hardware_amortization_hourly_cost",
          label: "Hardware hourly cost",
          type: "number",
          min: 0,
          step: 0.0001,
        },
        { name: "public_key", label: "Public key", type: "textarea", rows: 4, fullWidth: true },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "display_name", title: "Name", type: "text", width: 200 },
        { key: "node_id", title: "Node ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "hostname", title: "Hostname", type: "text", width: 180 },
        { key: "location", title: "Location", type: "text", width: 140 },
        { key: "pools", title: "Pools", type: "tags", width: 200 },
        { key: "last_heartbeat_at", title: "Heartbeat", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "enrollment",
          label: "Enrollment secret",
          icon: <KeyOutlined />,
          request: (row) => ({
            method: "POST",
            path: `/cavadalabs/nodes/${row.node_id}/enrollment-secrets`,
            body: { expires_in_seconds: 3600 },
          }),
        },
      ],
    },
    modelLoadRequests: {
      key: "modelLoadRequests",
      title: "Model load queue",
      listPath: "/cavadalabs/model-load-requests",
      responseKey: "model_load_requests",
      rowKey: "model_load_request_id",
      createPath: "/cavadalabs/model-load-requests",
      createLabel: "Queue load",
      filters: [projectFilter, { name: "status", label: "Status", type: "select", options: status.runtime }],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions),
        {
          name: "model_alias",
          label: "Model alias",
          type: "text",
          required: true,
          defaultValue: "cavadalabs/qwen3-32b",
        },
        { name: "provider", label: "Provider", type: "text", required: true, defaultValue: "cavadalabs" },
        { name: "node_id", label: "Node", type: "select", options: nodeOptions },
        { name: "gpu_id", label: "GPU ID", type: "text" },
        { name: "priority", label: "Priority", type: "number", min: 1, defaultValue: 100 },
        { name: "expires_at", label: "Expires at", type: "date" },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "model_alias", title: "Model", type: "text", width: 220 },
        { key: "model_load_request_id", title: "Request ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "project_id", title: "Project", type: "id", width: 200 },
        { key: "node_id", title: "Node", type: "id", width: 180 },
        { key: "gpu_id", title: "GPU", type: "id", width: 180 },
        { key: "priority", title: "Priority", type: "number", width: 90 },
        { key: "requested_at", title: "Requested", type: "datetime", width: 170 },
      ],
      toolbarActions: [
        {
          key: "schedule",
          label: "Run scheduler",
          icon: <PlayCircleOutlined />,
          request: (filters) => ({
            method: "POST",
            path: "/cavadalabs/model-load-requests/schedule",
            body: {
              project_id: filters.project_id,
              take: 10,
              lock_ttl_seconds: 3600,
            },
          }),
        },
      ],
    },
    gpuLocks: {
      key: "gpuLocks",
      title: "GPU locks",
      listPath: "/cavadalabs/gpu-locks",
      responseKey: "gpu_locks",
      rowKey: "lock_id",
      createPath: "/cavadalabs/gpu-locks",
      createLabel: "New lock",
      filters: [projectFilter, { name: "status", label: "Status", type: "select", options: status.lock }],
      createFields: [
        { name: "node_id", label: "Node", type: "select", required: true, options: nodeOptions },
        { name: "gpu_id", label: "GPU ID", type: "text", required: true },
        { name: "model_id", label: "Model ID", type: "text", required: true },
        projectField(projectOptions),
        {
          name: "owner_type",
          label: "Owner type",
          type: "select",
          required: true,
          options: enumOptions(["manual", "model_load_request", "chatbot"]),
        },
        { name: "owner_id", label: "Owner ID", type: "text", required: true },
        { name: "priority", label: "Priority", type: "number", min: 1, required: true, defaultValue: 100 },
        { name: "expires_at", label: "Expires at", type: "date", required: true },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "lock_id", title: "Lock ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "node_id", title: "Node", type: "id", width: 180 },
        { key: "gpu_id", title: "GPU", type: "id", width: 180 },
        { key: "model_id", title: "Model", type: "text", width: 220 },
        { key: "owner_type", title: "Owner", type: "status", width: 140 },
        { key: "expires_at", title: "Expires", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "release",
          label: "Release",
          danger: true,
          icon: <UnlockOutlined />,
          confirmTitle: "Release GPU lock",
          request: (row) => ({ method: "POST", path: `/cavadalabs/gpu-locks/${row.lock_id}/release` }),
        },
      ],
    },
    ragCollections: {
      key: "ragCollections",
      title: "RAG collections",
      listPath: "/cavadalabs/rag-collections",
      responseKey: "rag_collections",
      rowKey: "collection_id",
      createPath: "/cavadalabs/rag-collections",
      createLabel: "New collection",
      filters: [
        companyFilter,
        projectFilter,
        { name: "status", label: "Status", type: "select", options: status.ragCollection },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "scope", label: "Scope", type: "select", options: ragScopeOptions, defaultValue: "project" },
        { name: "status", label: "Status", type: "select", options: status.ragCollection, defaultValue: "draft" },
        { name: "description", label: "Description", type: "textarea", rows: 3, fullWidth: true },
        { name: "source_type", label: "Source type", type: "text" },
        { name: "vector_store_provider", label: "Vector store provider", type: "text" },
        { name: "vector_store_id", label: "Vector store ID", type: "text" },
        { name: "embedding_model", label: "Embedding model", type: "text" },
        jsonField("chunking_strategy", "Chunking strategy"),
        jsonField("access_policy", "Access policy"),
        jsonField("retention_policy", "Retention policy"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 220 },
        { key: "collection_id", title: "Collection ID", type: "id", width: 220 },
        { key: "scope", title: "Scope", type: "status", width: 110 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "vector_store_provider", title: "Vector store", type: "text", width: 150 },
        { key: "embedding_model", title: "Embedding", type: "text", width: 200 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    ragDocuments: {
      key: "ragDocuments",
      title: "RAG documents",
      listPath: "/cavadalabs/rag-documents",
      responseKey: "rag_documents",
      rowKey: "document_id",
      createPath: "/cavadalabs/rag-documents",
      createLabel: "Register document",
      filters: [
        collectionField(collectionOptions),
        companyFilter,
        projectFilter,
        { name: "status", label: "Status", type: "select", options: status.ragDocument },
      ],
      createFields: [
        collectionField(collectionOptions, true),
        { name: "source_uri", label: "Source URI", type: "text", fullWidth: true },
        { name: "file_name", label: "File name", type: "text" },
        { name: "mime_type", label: "MIME type", type: "text" },
        { name: "status", label: "Status", type: "select", options: status.ragDocument, defaultValue: "queued" },
        { name: "content_hash", label: "Content hash", type: "text" },
        { name: "byte_size", label: "Byte size", type: "number", min: 0 },
        { name: "token_count", label: "Token count", type: "number", min: 0 },
        { name: "chunk_count", label: "Chunk count", type: "number", min: 0, defaultValue: 0 },
        { name: "version", label: "Version", type: "number", min: 1, defaultValue: 1 },
        { name: "failure_reason", label: "Failure reason", type: "textarea", rows: 3, fullWidth: true },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "file_name", title: "File", type: "text", width: 220 },
        { key: "document_id", title: "Document ID", type: "id", width: 220 },
        { key: "collection_id", title: "Collection", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "token_count", title: "Tokens", type: "number", width: 100 },
        { key: "chunk_count", title: "Chunks", type: "number", width: 100 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    ragAssignments: {
      key: "ragAssignments",
      title: "RAG assignments",
      listPath: "/cavadalabs/rag-assignments",
      responseKey: "rag_assignments",
      rowKey: "assignment_id",
      createPath: "/cavadalabs/rag-assignments",
      createLabel: "Assign collection",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        collectionField(collectionOptions),
        { name: "status", label: "Status", type: "select", options: status.assignment },
      ],
      createFields: [
        chatbotField(chatbotOptions, true),
        collectionField(collectionOptions, true),
        { name: "status", label: "Status", type: "select", options: status.assignment, defaultValue: "active" },
        { name: "priority", label: "Priority", type: "number", min: 1, defaultValue: 100 },
        jsonField("retrieval_config", "Retrieval config"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "assignment_id", title: "Assignment ID", type: "id", width: 220 },
        { key: "chatbot_id", title: "Chatbot", type: "id", width: 220 },
        { key: "collection_id", title: "Collection", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "priority", title: "Priority", type: "number", width: 90 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    billingReports: {
      key: "billingReports",
      title: "Billing reports",
      listPath: "/cavadalabs/billing-reports",
      responseKey: "billing_reports",
      rowKey: "report_id",
      createPath: "/cavadalabs/billing-reports",
      createLabel: "Generate report",
      filters: [companyFilter],
      createFields: [
        companyField(companyOptions),
        {
          name: "year",
          label: "Year",
          type: "number",
          min: 2000,
          max: 2100,
          required: true,
          defaultValue: new Date().getFullYear(),
        },
        {
          name: "month",
          label: "Month",
          type: "number",
          min: 1,
          max: 12,
          required: true,
          defaultValue: new Date().getMonth() + 1,
        },
        {
          name: "formats",
          label: "Formats",
          type: "multiSelect",
          options: jsonFormats,
          defaultValue: ["json", "csv", "xlsx", "pdf"],
          required: true,
        },
        { name: "currency", label: "Currency", type: "text", defaultValue: "EUR" },
        { name: "tax_rate", label: "Tax rate", type: "number", min: 0, max: 1, step: 0.0001 },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "report_id", title: "Report ID", type: "id", width: 220 },
        { key: "company_id", title: "Company", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "total_requests", title: "Requests", type: "number", width: 110 },
        { key: "total_tokens", title: "Tokens", type: "number", width: 110 },
        { key: "grand_total", title: "Grand total", type: "currency", width: 130 },
        { key: "generated_at", title: "Generated", type: "datetime", width: 170 },
      ],
    },
    guardrailPolicies: {
      key: "guardrailPolicies",
      title: "Guardrail policies",
      listPath: "/cavadalabs/guardrail-policies",
      responseKey: "guardrail_policies",
      rowKey: "policy_id",
      createPath: "/cavadalabs/guardrail-policies",
      createLabel: "New guardrail policy",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        { name: "status", label: "Status", type: "select", options: status.guardrail },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        chatbotField(chatbotOptions, false),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "version", label: "Version", type: "number", min: 1, defaultValue: 1 },
        { name: "scope", label: "Scope", type: "select", options: scopeOptions, defaultValue: "company" },
        { name: "status", label: "Status", type: "select", options: status.guardrail, defaultValue: "draft" },
        {
          name: "enforcement_mode",
          label: "Enforcement",
          type: "select",
          options: enumOptions(["enforce", "log_only"]),
          defaultValue: "enforce",
        },
        { name: "description", label: "Description", type: "textarea", rows: 3, fullWidth: true },
        { name: "categories", label: "Categories", type: "tags", fullWidth: true },
        { name: "blocked_patterns", label: "Blocked patterns", type: "tags", fullWidth: true },
        { name: "pii_detection_enabled", label: "PII detection", type: "switch", defaultValue: true },
        {
          name: "prompt_injection_detection_enabled",
          label: "Prompt injection detection",
          type: "switch",
          defaultValue: true,
        },
        { name: "log_raw_content", label: "Log raw content", type: "switch", defaultValue: false },
        jsonField("rules", "Rules"),
        jsonField("redaction_patterns", "Redaction patterns"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 220 },
        { key: "policy_id", title: "Policy ID", type: "id", width: 220 },
        { key: "scope", title: "Scope", type: "status", width: 110 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "enforcement_mode", title: "Mode", type: "status", width: 120 },
        { key: "categories", title: "Categories", type: "tags", width: 220 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
      rowActions: [
        {
          key: "activate",
          label: "Activate",
          icon: <CheckCircleOutlined />,
          request: (row) => ({ method: "POST", path: `/cavadalabs/guardrail-policies/${row.policy_id}/activate` }),
        },
      ],
    },
    guardrailDecisions: {
      key: "guardrailDecisions",
      title: "Guardrail decisions",
      listPath: "/cavadalabs/guardrail-decisions",
      responseKey: "guardrail_decisions",
      rowKey: "decision_id",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        {
          name: "decision",
          label: "Decision",
          type: "select",
          options: enumOptions(["allow", "block", "redact", "review", "log_only"]),
        },
      ],
      columns: [
        { key: "decision_id", title: "Decision ID", type: "id", width: 220 },
        { key: "policy_name", title: "Policy", type: "text", width: 180 },
        { key: "phase", title: "Phase", type: "status", width: 120 },
        { key: "decision", title: "Decision", type: "status", width: 110 },
        { key: "action", title: "Action", type: "status", width: 110 },
        { key: "confidence", title: "Confidence", type: "number", width: 110 },
        { key: "latency_ms", title: "Latency", type: "number", width: 100 },
        { key: "created_at", title: "Created", type: "datetime", width: 170 },
      ],
    },
    complianceDocuments: {
      key: "complianceDocuments",
      title: "Compliance documents",
      listPath: "/cavadalabs/compliance-documents",
      responseKey: "compliance_documents",
      rowKey: "document_id",
      createPath: "/cavadalabs/compliance-documents",
      createLabel: "New document",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        collectionField(collectionOptions),
        { name: "framework", label: "Framework", type: "select", options: frameworkOptions },
        { name: "status", label: "Status", type: "select", options: status.compliance },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        chatbotField(chatbotOptions, false),
        collectionField(collectionOptions, false),
        { name: "framework", label: "Framework", type: "select", options: frameworkOptions, defaultValue: "gdpr" },
        { name: "document_type", label: "Document type", type: "text", required: true },
        { name: "title", label: "Title", type: "text", required: true },
        { name: "version", label: "Version", type: "number", min: 1, defaultValue: 1 },
        { name: "status", label: "Status", type: "select", options: status.compliance, defaultValue: "draft" },
        { name: "locale", label: "Locale", type: "text", defaultValue: "en" },
        { name: "content_format", label: "Content format", type: "text", defaultValue: "markdown" },
        { name: "approved_by", label: "Approved by", type: "text" },
        { name: "approved_at", label: "Approved at", type: "date" },
        { name: "published_at", label: "Published at", type: "date" },
        { name: "valid_from", label: "Valid from", type: "date" },
        { name: "valid_until", label: "Valid until", type: "date" },
        { name: "content", label: "Content", type: "textarea", rows: 8, fullWidth: true, emptyValue: "emptyString" },
        jsonField("generated_from", "Generated from"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "title", title: "Title", type: "text", width: 260 },
        { key: "document_id", title: "Document ID", type: "id", width: 220 },
        { key: "framework", title: "Framework", type: "status", width: 120 },
        { key: "document_type", title: "Type", type: "status", width: 150 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "version", title: "Version", type: "number", width: 90 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    complianceEvidence: {
      key: "complianceEvidence",
      title: "Compliance evidence",
      listPath: "/cavadalabs/compliance-evidence",
      responseKey: "compliance_evidence",
      rowKey: "evidence_id",
      createPath: "/cavadalabs/compliance-evidence",
      createLabel: "New evidence",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        collectionField(collectionOptions),
        { name: "framework", label: "Framework", type: "select", options: frameworkOptions },
        { name: "status", label: "Status", type: "select", options: status.compliance },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        chatbotField(chatbotOptions, false),
        collectionField(collectionOptions, false),
        { name: "framework", label: "Framework", type: "select", options: frameworkOptions, required: true },
        { name: "evidence_type", label: "Evidence type", type: "text", required: true },
        { name: "title", label: "Title", type: "text", required: true },
        { name: "status", label: "Status", type: "select", options: status.compliance, defaultValue: "active" },
        { name: "source_type", label: "Source type", type: "text" },
        { name: "source_id", label: "Source ID", type: "text" },
        { name: "captured_at", label: "Captured at", type: "date" },
        { name: "expires_at", label: "Expires at", type: "date" },
        jsonField("content", "Content"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "title", title: "Title", type: "text", width: 240 },
        { key: "evidence_id", title: "Evidence ID", type: "id", width: 220 },
        { key: "framework", title: "Framework", type: "status", width: 120 },
        { key: "evidence_type", title: "Type", type: "status", width: 150 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "captured_at", title: "Captured", type: "datetime", width: 170 },
        { key: "expires_at", title: "Expires", type: "datetime", width: 170 },
      ],
    },
    processingActivities: {
      key: "processingActivities",
      title: "Processing activities",
      listPath: "/cavadalabs/processing-activities",
      responseKey: "processing_activities",
      rowKey: "activity_id",
      createPath: "/cavadalabs/processing-activities",
      createLabel: "New activity",
      filters: [
        companyFilter,
        projectFilter,
        { name: "status", label: "Status", type: "select", options: status.compliance },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "status", label: "Status", type: "select", options: status.compliance, defaultValue: "active" },
        { name: "controller", label: "Controller", type: "text" },
        { name: "processor", label: "Processor", type: "text" },
        { name: "legal_basis", label: "Legal basis", type: "text" },
        { name: "retention_period", label: "Retention period", type: "text" },
        { name: "purpose", label: "Purpose", type: "textarea", rows: 4, required: true, fullWidth: true },
        { name: "data_categories", label: "Data categories", type: "tags", fullWidth: true },
        { name: "data_subject_categories", label: "Data subject categories", type: "tags", fullWidth: true },
        { name: "recipients", label: "Recipients", type: "tags", fullWidth: true },
        { name: "transfer_countries", label: "Transfer countries", type: "tags", fullWidth: true },
        { name: "security_measures", label: "Security measures", type: "tags", fullWidth: true },
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 240 },
        { key: "activity_id", title: "Activity ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "legal_basis", title: "Legal basis", type: "text", width: 180 },
        { key: "data_categories", title: "Data categories", type: "tags", width: 240 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
    dataSubjectRequests: {
      key: "dataSubjectRequests",
      title: "Data subject requests",
      listPath: "/cavadalabs/data-subject-requests",
      responseKey: "data_subject_requests",
      rowKey: "dsr_id",
      createPath: "/cavadalabs/data-subject-requests",
      createLabel: "New DSR",
      filters: [companyFilter, projectFilter, { name: "status", label: "Status", type: "select", options: status.dsr }],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        { name: "requester_email", label: "Requester email", type: "text", required: true },
        {
          name: "request_type",
          label: "Request type",
          type: "select",
          required: true,
          options: enumOptions(["access", "erasure", "rectification", "export", "restriction", "objection"]),
        },
        { name: "status", label: "Status", type: "select", options: status.dsr, defaultValue: "received" },
        { name: "due_at", label: "Due at", type: "date" },
        { name: "assigned_to", label: "Assigned to", type: "text" },
        jsonField("scope", "Scope"),
        jsonField("result", "Result"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "requester_email", title: "Requester", type: "text", width: 220 },
        { key: "dsr_id", title: "DSR ID", type: "id", width: 220 },
        { key: "request_type", title: "Type", type: "status", width: 130 },
        { key: "status", title: "Status", type: "status", width: 160 },
        { key: "due_at", title: "Due", type: "datetime", width: 170 },
        { key: "assigned_to", title: "Assignee", type: "text", width: 160 },
      ],
    },
    aiSystemAssessments: {
      key: "aiSystemAssessments",
      title: "AI system assessments",
      listPath: "/cavadalabs/ai-system-assessments",
      responseKey: "ai_system_assessments",
      rowKey: "assessment_id",
      createPath: "/cavadalabs/ai-system-assessments",
      createLabel: "New assessment",
      filters: [
        companyFilter,
        projectFilter,
        chatbotField(chatbotOptions),
        { name: "status", label: "Status", type: "select", options: status.compliance },
        {
          name: "risk_classification",
          label: "Risk",
          type: "select",
          options: enumOptions(["unknown", "minimal", "limited", "high", "prohibited"]),
        },
      ],
      createFields: [
        companyField(companyOptions),
        projectField(projectOptions, false),
        chatbotField(chatbotOptions, false),
        { name: "name", label: "Name", type: "text", required: true },
        { name: "version", label: "Version", type: "number", min: 1, defaultValue: 1 },
        { name: "status", label: "Status", type: "select", options: status.compliance, defaultValue: "draft" },
        {
          name: "risk_classification",
          label: "Risk classification",
          type: "select",
          options: enumOptions(["unknown", "minimal", "limited", "high", "prohibited"]),
          defaultValue: "unknown",
        },
        {
          name: "intended_purpose",
          label: "Intended purpose",
          type: "textarea",
          rows: 4,
          required: true,
          fullWidth: true,
        },
        { name: "transparency_notice", label: "Transparency notice", type: "textarea", rows: 4, fullWidth: true },
        { name: "approved_by", label: "Approved by", type: "text" },
        { name: "approved_at", label: "Approved at", type: "date" },
        jsonField("prohibited_practice_review", "Prohibited practice review"),
        jsonField("human_oversight", "Human oversight"),
        jsonField("model_provider_metadata", "Model provider metadata"),
        jsonField("evaluation_evidence", "Evaluation evidence"),
        jsonField("metadata", "Metadata"),
      ],
      columns: [
        { key: "name", title: "Name", type: "text", width: 240 },
        { key: "assessment_id", title: "Assessment ID", type: "id", width: 220 },
        { key: "status", title: "Status", type: "status", width: 110 },
        { key: "risk_classification", title: "Risk", type: "status", width: 130 },
        { key: "version", title: "Version", type: "number", width: 90 },
        { key: "updated_at", title: "Updated", type: "datetime", width: 170 },
      ],
    },
  };
};
